spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://db:5432/bootcamp-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/realms/Demo-Realm"
          jwk-set-uri: "http://keycloak:8080/realms/Demo-Realm/protocol/openid-connect/certs"